### ISSUE TITLE
NotImplementedError: Can't perform this operation for unregistered loader type

### ISSUE THREAD

**Issue by toren77** [PacktPublishing/Python-Programming-Blueprints#13]
Thank you for the very intresting book !

I get error while trying to execute code from Chapter 5 - "Putting it all together"
installed jinja2-2.10

I try to execute http://localhost:8000/ in browser and get following error 

(temp_messenger) C:\Users\user\Envs\temp_messenger>nameko run temp_messenger.service --config config.yaml
starting services: message_service, web_server
Connected to amqp://guest:**@127.0.0.1:5672//
Connected to amqp://guest:**@127.0.0.1:5672//
error handling worker <WorkerContext [web_server.home] at 0x146e6affcc0>: Can't perform this opera
tion for unregistered loader type
Traceback (most recent call last):
  File "c:\users\user\envs\temp_messenger\lib\site-packages\nameko\containers.py", line 388, in _ru
n_worker
    result = method(*worker_ctx.args, **worker_ctx.kwargs)
  File ".\temp_messenger\service.py", line 16, in home
    rendered_template = self.jinja.render_home(messages)
  File ".\temp_messenger\dependencies\jinja2.py", line 28, in render_home
    template = self.template_env.get_template('home.html')
  File "c:\users\user\envs\temp_messenger\lib\site-packages\jinja2\environment.py", line 830, in ge
t_template
    return self._load_template(name, self.make_globals(globals))
  File "c:\users\user\envs\temp_messenger\lib\site-packages\jinja2\environment.py", line 804, in _l
oad_template
    template = self.loader.load(self, name, globals)
  File "c:\users\user\envs\temp_messenger\lib\site-packages\jinja2\loaders.py", line 113, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "c:\users\user\envs\temp_messenger\lib\site-packages\jinja2\loaders.py", line 234, in get_so
urce
    if not self.provider.has_resource(p):
  File "c:\users\user\envs\temp_messenger\lib\site-packages\pkg_resources\__init__.py", line 1399,
in has_resource
    return self._has(self._fn(self.module_path, resource_name))
  File "c:\users\user\envs\temp_messenger\lib\site-packages\pkg_resources\__init__.py", line 1452,
in _has
    "Can't perform this operation for unregistered loader type"
NotImplementedError: Can't perform this operation for unregistered loader type
127.0.0.1 - - [23/Oct/2018 10:03:19] "GET / HTTP/1.1" 500 246 1.074965

**Comment by toren77** [comment]
code here : https://github.com/toren77/Python-Programming-Blueprints-Ch5-code/tree/master/temp_messenger

**Comment by toren77** [comment]
I solved the problem by adding __init__.py under temp_messenger folder
see [reference](https://stackoverflow.com/questions/37069303/notimplementederror-cant-perform-this-operation-for-unregistered-loader-type) :

**Comment by dfurtado** [comment]
Hi @toren77 

Thank you so much for the feedback and for reporting the issue. I will make sure to add the `__init__.py` file here in the repository.

Best Regards,

//Daniel
