### ISSUE TITLE
A process in the process pool was terminated abruptly while the future was running or pending

### ISSUE THREAD

**Issue by xiillii** [PacktPublishing/Python-Programming-Blueprints#16]
When I run chapter 3 TwitterVotes on Windows, all goes very well, but in MacOS Mojave, it crashes with the error:

Exception in Tkinter callback
Traceback (most recent call last):
  File "/Users/xiillii/OneDrive/Programas/Python/EnvMacos/twittervotes/lib/python3.7/site-packages/rx/linq/observable/fromfuture.py", line 22, in done
    value = future.result()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/_base.py", line 425, in result
    return self.__get_result()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
concurrent.futures.process.BrokenProcessPool: A process in the process pool was terminated abruptly while the future was running or pending.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/tkinter/__init__.py", line 1705, in __call__
    return self.func(*args)
  File "app.py", line 64, in _fetch_data
    self._runner.exec(execute_request, self._manager.hashtags)
  File "/Users/xiillii/OneDrive/Programas/Python/Projects/twittervotes/core/runner.py", line 26, in exec
    self._on_complete)
  File "/Users/xiillii/OneDrive/Programas/Python/EnvMacos/twittervotes/lib/python3.7/site-packages/rx/core/observablebase.py", line 83, in subscribe
    current_thread_scheduler.schedule(set_disposable)
  File "/Users/xiillii/OneDrive/Programas/Python/EnvMacos/twittervotes/lib/python3.7/site-packages/rx/concurrency/currentthreadscheduler.py", line 50, in schedule
    return self.schedule_relative(timedelta(0), action, state)
  File "/Users/xiillii/OneDrive/Programas/Python/EnvMacos/twittervotes/lib/python3.7/site-packages/rx/concurrency/currentthreadscheduler.py", line 67, in schedule_relative
    Trampoline.run(queue)
  File "/Users/xiillii/OneDrive/Programas/Python/EnvMacos/twittervotes/lib/python3.7/site-packages/rx/concurrency/currentthreadscheduler.py", line 31, in run
    item.invoke()
  File "/Users/xiillii/OneDrive/Programas/Python/EnvMacos/twittervotes/lib/python3.7/site-packages/rx/concurrency/scheduleditem.py", line 17, in invoke
    ret = self.scheduler.invoke_action(self.action, self.state)
  File "/Users/xiillii/OneDrive/Programas/Python/EnvMacos/twittervotes/lib/python3.7/site-packages/rx/concurrency/schedulerbase.py", line 14, in invoke_action
    ret = action(self, state)
  File "/Users/xiillii/OneDrive/Programas/Python/EnvMacos/twittervotes/lib/python3.7/site-packages/rx/core/observablebase.py", line 67, in set_disposable
    subscriber = self._subscribe_core(auto_detach_observer)
  File "/Users/xiillii/OneDrive/Programas/Python/EnvMacos/twittervotes/lib/python3.7/site-packages/rx/core/anonymousobservable.py", line 20, in _subscribe_core
    return self._subscribe(observer)
  File "/Users/xiillii/OneDrive/Programas/Python/EnvMacos/twittervotes/lib/python3.7/site-packages/rx/linq/observable/merge.py", line 143, in subscribe
    m.disposable = sources.subscribe(on_next, observer.on_error, on_completed)
  File "/Users/xiillii/OneDrive/Programas/Python/EnvMacos/twittervotes/lib/python3.7/site-packages/rx/core/observablebase.py", line 85, in subscribe
    set_disposable()
  File "/Users/xiillii/OneDrive/Programas/Python/EnvMacos/twittervotes/lib/python3.7/site-packages/rx/core/observablebase.py", line 67, in set_disposable
    subscriber = self._subscribe_core(auto_detach_observer)
  File "/Users/xiillii/OneDrive/Programas/Python/EnvMacos/twittervotes/lib/python3.7/site-packages/rx/core/anonymousobservable.py", line 20, in _subscribe_core
    return self._subscribe(observer)
  File "/Users/xiillii/OneDrive/Programas/Python/EnvMacos/twittervotes/lib/python3.7/site-packages/rx/linq/observable/fromiterable.py", line 44, in subscribe
    sd.disposable = scheduler.schedule(action)
  File "/Users/xiillii/OneDrive/Programas/Python/EnvMacos/twittervotes/lib/python3.7/site-packages/rx/concurrency/immediatescheduler.py", line 12, in schedule
    return self.invoke_action(action, state)
  File "/Users/xiillii/OneDrive/Programas/Python/EnvMacos/twittervotes/lib/python3.7/site-packages/rx/concurrency/schedulerbase.py", line 14, in invoke_action
    ret = action(self, state)
  File "/Users/xiillii/OneDrive/Programas/Python/EnvMacos/twittervotes/lib/python3.7/site-packages/rx/linq/observable/fromiterable.py", line 41, in action
    observer.on_next(item)
  File "/Users/xiillii/OneDrive/Programas/Python/EnvMacos/twittervotes/lib/python3.7/site-packages/rx/core/observerbase.py", line 19, in on_next
    self._on_next_core(value)
  File "/Users/xiillii/OneDrive/Programas/Python/EnvMacos/twittervotes/lib/python3.7/site-packages/rx/core/autodetachobserver.py", line 16, in _on_next_core
    self.observer.on_next(value)
  File "/Users/xiillii/OneDrive/Programas/Python/EnvMacos/twittervotes/lib/python3.7/site-packages/rx/core/observerbase.py", line 19, in on_next
    self._on_next_core(value)
  File "/Users/xiillii/OneDrive/Programas/Python/EnvMacos/twittervotes/lib/python3.7/site-packages/rx/core/anonymousobserver.py", line 14, in _on_next_core
    self._next(value)
  File "/Users/xiillii/OneDrive/Programas/Python/EnvMacos/twittervotes/lib/python3.7/site-packages/rx/linq/observable/merge.py", line 135, in on_next
    disposable = inner_source.subscribe(on_next, observer.on_error, on_completed)
  File "/Users/xiillii/OneDrive/Programas/Python/EnvMacos/twittervotes/lib/python3.7/site-packages/rx/core/observablebase.py", line 85, in subscribe
    set_disposable()
  File "/Users/xiillii/OneDrive/Programas/Python/EnvMacos/twittervotes/lib/python3.7/site-packages/rx/core/observablebase.py", line 67, in set_disposable
    subscriber = self._subscribe_core(auto_detach_observer)
  File "/Users/xiillii/OneDrive/Programas/Python/EnvMacos/twittervotes/lib/python3.7/site-packages/rx/core/anonymousobservable.py", line 20, in _subscribe_core
    return self._subscribe(observer)
  File "/Users/xiillii/OneDrive/Programas/Python/EnvMacos/twittervotes/lib/python3.7/site-packages/rx/linq/observable/fromfuture.py", line 29, in subscribe
    future.add_done_callback(done)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/_base.py", line 403, in add_done_callback
    fn(self)
  File "/Users/xiillii/OneDrive/Programas/Python/EnvMacos/twittervotes/lib/python3.7/site-packages/rx/linq/observable/fromfuture.py", line 24, in done
    observer.on_error(ex)
  File "/Users/xiillii/OneDrive/Programas/Python/EnvMacos/twittervotes/lib/python3.7/site-packages/rx/core/observerbase.py", line 33, in on_error
    self._on_error_core(error)
  File "/Users/xiillii/OneDrive/Programas/Python/EnvMacos/twittervotes/lib/python3.7/site-packages/rx/core/autodetachobserver.py", line 23, in _on_error_core
    self.observer.on_error(exn)
  File "/Users/xiillii/OneDrive/Programas/Python/EnvMacos/twittervotes/lib/python3.7/site-packages/rx/core/observerbase.py", line 33, in on_error
    self._on_error_core(error)
  File "/Users/xiillii/OneDrive/Programas/Python/EnvMacos/twittervotes/lib/python3.7/site-packages/rx/core/anonymousobserver.py", line 17, in _on_error_core
    self._error(error)
  File "/Users/xiillii/OneDrive/Programas/Python/EnvMacos/twittervotes/lib/python3.7/site-packages/rx/core/observerbase.py", line 33, in on_error
    self._on_error_core(error)
  File "/Users/xiillii/OneDrive/Programas/Python/EnvMacos/twittervotes/lib/python3.7/site-packages/rx/core/autodetachobserver.py", line 23, in _on_error_core
    self.observer.on_error(exn)
  File "/Users/xiillii/OneDrive/Programas/Python/EnvMacos/twittervotes/lib/python3.7/site-packages/rx/core/observerbase.py", line 33, in on_error
    self._on_error_core(error)
  File "/Users/xiillii/OneDrive/Programas/Python/EnvMacos/twittervotes/lib/python3.7/site-packages/rx/core/anonymousobserver.py", line 17, in _on_error_core
    self._error(error)
  File "app.py", line 68, in _on_error
    raise Exception(error_message)
Exception: A process in the process pool was terminated abruptly while the future was running or pending.
(twittervotes) xfiles:twittervotes xiillii$ pip install -r requirements.txt 
Requirement already satisfied: Flask in /Users/xiillii/OneDrive/Programas/Python/EnvMacos/twittervotes/lib/python3.7/site-packages (from -r requirements.txt (line 1)) (0.12.2)
Requirement already satisfied: oauth2 in /Users/xiillii/OneDrive/Programas/Python/EnvMacos/twittervotes/lib/python3.7/site-packages (from -r requirements.txt (line 2)) (1.9.0.post1)
Requirement already satisfied: PyYAML in /Users/xiillii/OneDrive/Programas/Python/EnvMacos/twittervotes/lib/python3.7/site-packages (from -r requirements.txt (line 3)) (3.12)
Requirement already satisfied: requests in /Users/xiillii/OneDrive/Programas/Python/EnvMacos/twittervotes/lib/python3.7/site-packages (from -r requirements.txt (line 4)) (2.18.4)
Requirement already satisfied: Rx in /Users/xiillii/OneDrive/Programas/Python/EnvMacos/twittervotes/lib/python3.7/site-packages (from -r requirements.txt (line 5)) (1.6.0)
Requirement already satisfied: autopep8 in /Users/xiillii/OneDrive/Programas/Python/EnvMacos/twittervotes/lib/python3.7/site-packages (from -r requirements.txt (line 6)) (1.4.4)
Requirement already satisfied: itsdangerous>=0.21 in /Users/xiillii/OneDrive/Programas/Python/EnvMacos/twittervotes/lib/python3.7/site-packages (from Flask->-r requirements.txt (line 1)) (1.1.0)
Requirement already satisfied: Werkzeug>=0.7 in /Users/xiillii/OneDrive/Programas/Python/EnvMacos/twittervotes/lib/python3.7/site-packages (from Flask->-r requirements.txt (line 1)) (0.15.2)
Requirement already satisfied: click>=2.0 in /Users/xiillii/OneDrive/Programas/Python/EnvMacos/twittervotes/lib/python3.7/site-packages (from Flask->-r requirements.txt (line 1)) (7.0)
Requirement already satisfied: Jinja2>=2.4 in /Users/xiillii/OneDrive/Programas/Python/EnvMacos/twittervotes/lib/python3.7/site-packages (from Flask->-r requirements.txt (line 1)) (2.10.1)
Requirement already satisfied: httplib2 in /Users/xiillii/OneDrive/Programas/Python/EnvMacos/twittervotes/lib/python3.7/site-packages (from oauth2->-r requirements.txt (line 2)) (0.12.3)
Requirement already satisfied: certifi>=2017.4.17 in /Users/xiillii/OneDrive/Programas/Python/EnvMacos/twittervotes/lib/python3.7/site-packages (from requests->-r requirements.txt (line 4)) (2019.3.9)
Requirement already satisfied: urllib3<1.23,>=1.21.1 in /Users/xiillii/OneDrive/Programas/Python/EnvMacos/twittervotes/lib/python3.7/site-packages (from requests->-r requirements.txt (line 4)) (1.22)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /Users/xiillii/OneDrive/Programas/Python/EnvMacos/twittervotes/lib/python3.7/site-packages (from requests->-r requirements.txt (line 4)) (3.0.4)
Requirement already satisfied: idna<2.7,>=2.5 in /Users/xiillii/OneDrive/Programas/Python/EnvMacos/twittervotes/lib/python3.7/site-packages (from requests->-r requirements.txt (line 4)) (2.6)
Requirement already satisfied: pycodestyle>=2.4.0 in /Users/xiillii/OneDrive/Programas/Python/EnvMacos/twittervotes/lib/python3.7/site-packages (from autopep8->-r requirements.txt (line 6)) (2.5.0)
Requirement already satisfied: MarkupSafe>=0.23 in /Users/xiillii/OneDrive/Programas/Python/EnvMacos/twittervotes/lib/python3.7/site-packages (from Jinja2>=2.4->Flask->-r requirements.txt (line 1)) (1.1.1)

**Comment by deepesh-packt** [comment]
Please reopen if the issue still persists.
