### ISSUE TITLE
ModuleNotFoundError: No module named 'weatherterm.parsers.'

### ISSUE THREAD

**Issue by wardspan** [PacktPublishing/Python-Programming-Blueprints#6]
Using the code I pulled down from git I cant get things to run correctly either.
(weatherterm) firefly:wardspan[Chapter01]$ python --version
Python 3.6.4
(weatherterm) firefly:wardspan[Chapter01]$ python -m weatherterm -u Fahrenheit -a SWXX2372:1:SW -p WeatherComParser -10d
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.6.4_4/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/Cellar/python/3.6.4_4/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/wardspan/Code/Python-Programming-Blueprints/Chapter01/weatherterm/__main__.py", line 18, in <module>
    parsers = parser_loader.load('./weatherterm/parsers')
  File "/Users/wardspan/Code/Python-Programming-Blueprints/Chapter01/weatherterm/core/parser_loader.py", line 33, in load
    return _import_parsers(parserfiles)
  File "/Users/wardspan/Code/Python-Programming-Blueprints/Chapter01/weatherterm/core/parser_loader.py", line 19, in _import_parsers
    0)
ModuleNotFoundError: No module named 'weatherterm.parsers.'

**Comment by dfurtado** [comment]
Hi @wardspan 

Please, try creating a file called `__init__.py` inside of the directory `weatherterm/parsers`

**Comment by wardspan** [comment]
@dfurtado 

(weatherterm) firefly:wardspan[parsers]$ touch __init__.py
(weatherterm) firefly:wardspan[parsers]$ ls
__init__.py           weather_com_parser.py
(weatherterm) firefly:wardspan[Chapter01]$ python3 -m weatherterm -u Fahrenheit -a SWXX2372:1:SW -p WeatherComParser -10d
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.6.4_4/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/Cellar/python/3.6.4_4/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/wardspan/Code/Python-Programming-Blueprints/Chapter01/weatherterm/__main__.py", line 18, in <module>
    parsers = parser_loader.load('./weatherterm/parsers')
  File "/Users/wardspan/Code/Python-Programming-Blueprints/Chapter01/weatherterm/core/parser_loader.py", line 33, in load
    return _import_parsers(parserfiles)
  File "/Users/wardspan/Code/Python-Programming-Blueprints/Chapter01/weatherterm/core/parser_loader.py", line 19, in _import_parsers
    0)
ModuleNotFoundError: No module named 'weatherterm.parsers.'

**Comment by armaanreza** [comment]
Hi @wardspan,

As @dfurtado mentioned, you should use `$touch __init__.py` NOT `$touch init.py`

Regards

**Comment by wardspan** [comment]
That's what I did - markup messed it up. Still doesn't work -parser is not recognized in your own code.

**Comment by dfurtado** [comment]
Hi @wardspan ,

We are just trying to help you troubleshoot the problem. 

So creating the file `__init__.py` in the `weatherterm/parsers` directory didn't work, right? Could you please, send me your source code so I can have a closer look? You can zip the entire folder (excluding the phantomJS folder) and mail to `pythonblueprints@dfurtado.com`

I will be glad to have a look at your code and try to understand what is going wrong.

Best regards

**Comment by wardspan** [comment]
@dfurtado - understood - trying to figure out where the error is

I am using your code from the git repo - after mine didnt work I always download the authors code to see what I am doing wrong - in this case everything matches and I am still getting the same error when I use your code

**Comment by dfurtado** [comment]
@wardspan  - alright, is your code on the repo https://github.com/wardspan/weatherterm ?

**Comment by dfurtado** [comment]
@wardspan  I did a small update on the project. Could you please, pull the changes and see if it solves the problem?

**Comment by wardspan** [comment]
thanks @dfurtado the new code seems to be working correctly.
